version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      # to persist changes to the workspace, use a named volume or mapped host directory
      - ../..:/workspaces:cached
      # so hot reload works in the container
      - ../portfolio/src:/home/node/app/src
      - ../portfolio/src/lib:/home/node/app/src/lib
      - ../portfolio/src/assets:/home/node/app/src/assets
      - ../portfolio/static:/home/node/app/static
      - ../portfolio/vite.config.js:/home/node/app/vite.config.js
      - ../portfolio/tsconfig.json:/home/node/app/tsconfig.json
      - ../portfolio/svelte.config.js:/home/node/app/svelte.config.js

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
