name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Action test
        uses: berkkan22/remote-server-connector@main
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          server-host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          command: "cd /home/${{ secrets.USERNAME }}/svelte-portfolio/portfolio/ && git fetch --all && git reset --hard origin/main && git pull && docker build -t portfolio . && docker stop portfolio || true && docker run -itd --rm  -p 48605:80 --name portfolio portfolio"

  build_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: portfolio/package-lock.json

      - name: Install dependencies
        run: |
          cd portfolio
          npm ci

      - name: build
        env:
          BASE_PATH: "/${{ github.event.repository.name }}"
        run: |
          cd portfolio
          npm run build-gh

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "portfolio/dist/"

  deploy-to-github-pages:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
